version: "3.3"
services:
  dcs-postgres:
    image: postgres:15.3-alpine
    container_name: escritorios-postgres
    restart: always
    environment:
      POSTGRES_DB: escritorios
      POSTGRES_USER: escritorios
      POSTGRES_PASSWORD: escritorios
    ports:
      - 5436:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
